export * from "./auth.routes";
export * from "./user.routes";
export * from "./class.routes";
export * from "./coupon.routes";
export * from "./student.routes";
export * from "./transaction.routes";
export * from "./report.routes";
export * from "./academicYear.routes"
export * from "./platform.routes"
export * from "./principal.routes"
export * from "./parent.routes"
export * from "./attendance.routes"
export * from "./teacherAttendance.routes"
export * from "./leave.routes"
export * from "./studentPromotion.routes"
export * from "./classTeacher.routes"
export * from "./teacherStudentMapping.routes"
export * from "./teacher.routes"
export * from "./teacherMarks.routes"
export * from "./teacherLeave.routes"
export * from "./teacherProfile.routes"
export * from "./teacherTimetable.routes"
export * from "./adminDashboard.routes"
export * from "./adminAttendanceLeave.routes"
export * from "./bulkImportSession.routes"
