export * from "./auth.routes";
export * from "./user.routes";
export * from "./class.routes";
export * from "./coupon.routes";
export * from "./student.routes";
export * from "./transaction.routes";
export * from "./report.routes";
export * from "./academicYear.routes"
export * from "./platform.routes"
export * from "./principal.routes"
export * from "./parent.routes"
