export * from "./auth.controller";
export * from "./user.controller";
export * from "./class.controller";
export * from "./coupon.controller";
export * from "./student.controller";
export * from "./transaction.controller";
export * from "./report.controller";
export * from "./academicYear.controller";
export * from "./platform.controller"
export * from "./principal.controller";